name: deneme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
  
    sdk: flutter
  firebase_database: ^11.0.4
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  get_it: ^7.7.0
  fluttertoast: ^8.2.8
  provider: ^6.1.2
  ionicons: ^0.2.2
  nested: ^1.0.0
  shared_preferences: ^2.3.2
  uuid: ^4.4.2
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  

flutter:
  uses-material-design: true

