// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvhwC8E_HxwxYMI0z1Ri3doZfshpR6A48',
    appId: '1:735214350632:web:0c7b7146fcae5f1cb7201d',
    messagingSenderId: '735214350632',
    projectId: 'etkinlik-firebasee',
    authDomain: 'etkinlik-firebasee.firebaseapp.com',
    storageBucket: 'etkinlik-firebasee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP-j6J9n7152qL_kME--9cyg4iFepvT8U',
    appId: '1:735214350632:android:c65983a715a78fedb7201d',
    messagingSenderId: '735214350632',
    projectId: 'etkinlik-firebasee',
    storageBucket: 'etkinlik-firebasee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgeaWYXuAmRM7s8667v_I_s6HSu4f4IJs',
    appId: '1:735214350632:ios:c3ecfc55f6688cb9b7201d',
    messagingSenderId: '735214350632',
    projectId: 'etkinlik-firebasee',
    storageBucket: 'etkinlik-firebasee.appspot.com',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgeaWYXuAmRM7s8667v_I_s6HSu4f4IJs',
    appId: '1:735214350632:ios:c3ecfc55f6688cb9b7201d',
    messagingSenderId: '735214350632',
    projectId: 'etkinlik-firebasee',
    storageBucket: 'etkinlik-firebasee.appspot.com',
    iosBundleId: 'com.example.deneme',
  );
}
